apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sopranobot-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: sopranobot 
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - default